"""
Business-flow workbook connector.

Ingests CP_Catalog_Business_Flows.xlsx (the 9-sheet workbook generated by the
enterprise prompt) into the dedicated bf_* tables. Self-contained: does not touch
the existing pipeline builder or api_business_flows.

Sheets handled (tolerant name matching, case/space-insensitive):
  1 API_Business_Flows   -> bf_api_flows
  2 API_Flow_Steps       -> bf_api_flow_steps
  3 Data_Pipelines       -> bf_pipelines
  4 Pipeline_Stages      -> bf_pipeline_stages
  5 Interface_360        -> bf_interfaces
  6 Flow_Datapoint_Map   -> bf_flow_datapoint_map (resolved vs dp_registry)
  7/9 Compression_Plan   -> bf_compression_plan
  8 Compression_Summary  -> bf_compression_summary

Env: BUSINESS_FLOWS_XLSX = path to the workbook.

Run AFTER datapoint_index (so dp_registry exists for Flow_Datapoint_Map to
resolve against) and BEFORE search_index (so new flows/pipelines get indexed).
Emits a mismatch report: data points referenced by flows that don't resolve to
an existing dp_registry entry (a migration/naming gap).
"""
from __future__ import annotations
import os
import logging

log = logging.getLogger("cp.business_flow")


def _norm(s):
    return "".join(ch for ch in str(s or "").lower() if ch.isalnum())


# canonical sheet name -> set of accepted normalized variants
SHEET_ALIASES = {
    "api_business_flows": {"apibusinessflows"},
    "api_flow_steps": {"apiflowsteps"},
    "data_pipelines": {"datapipelines"},
    "pipeline_stages": {"pipelinestages"},
    "interface_360": {"interface360"},
    "flow_datapoint_map": {"flowdatapointmap"},
    "compression_plan": {"compressionplan", "compressionplanv2"},        # v2 folds in
    "compression_summary": {"compressionsummary", "compressionsummaryv2"},  # v2 folds in
}


class BusinessFlowConnector:
    """Step name: business_flow."""

    def __init__(self, path=None):
        self.path = path or os.environ.get("BUSINESS_FLOWS_XLSX")

    @classmethod
    def from_env(cls, resolver=None):
        return cls()

    # ---- parse ----
    def parse(self):
        if not self.path or not os.path.exists(self.path):
            log.warning("business_flow: BUSINESS_FLOWS_XLSX not set or file missing (%s); skipping", self.path)
            return None
        from openpyxl import load_workbook
        wb = load_workbook(self.path, read_only=True, data_only=True)

        # map actual sheet titles to canonical keys (a canon key may have
        # several sheets, e.g. Compression_Plan + Compression_Plan_v2 -> both fold in)
        found = {}
        for title in wb.sheetnames:
            n = _norm(title)
            for canon, variants in SHEET_ALIASES.items():
                if n == _norm(canon) or n in variants:
                    found.setdefault(canon, []).append(title)
                    break
        bundle = {}
        for canon, titles in found.items():
            rows = []
            for title in titles:
                rows.extend(self._sheet_rows(wb[title]))
            bundle[canon] = rows
        wb.close()
        log.info("business_flow: parsed %d canonical sheets from %d source sheets",
                 len(bundle), sum(len(t) for t in found.values()))
        return bundle

    @staticmethod
    def _sheet_rows(ws):
        """Return list of dict rows keyed by normalized header."""
        rows = list(ws.iter_rows(values_only=True))
        if not rows:
            return []
        header = [_norm(h) for h in rows[0]]
        out = []
        for r in rows[1:]:
            if r is None or all(c is None or str(c).strip() == "" for c in r):
                continue
            out.append({header[i]: r[i] for i in range(min(len(header), len(r)))})
        return out

    @staticmethod
    def _g(row, *keys):
        """Get first present normalized key."""
        for k in keys:
            v = row.get(_norm(k))
            if v is not None and str(v).strip() != "":
                return str(v).strip()
        return None

    # ---- load ----
    def load(self, loader, bundle=None):
        if bundle is None:
            bundle = self.parse()
        if not bundle:
            return
        g = self._g
        conn = loader.conn
        cur = conn.cursor()

        # existing normalized datapoints (for Flow_Datapoint_Map resolution)
        known_dps = set()
        try:
            cur.execute("SELECT dp_name_normalized FROM dp_registry")
            known_dps = {(r[0] or "").lower() for r in cur.fetchall()}
        except Exception as e:
            log.warning("business_flow: could not read dp_registry (%s); resolution flags all N", e)

        counts = {}

        # 1. API_Business_Flows
        for row in bundle.get("api_business_flows", []):
            fid = g(row, "Flow_ID")
            if not fid:
                continue
            loader._merge("bf_api_flows", ("flow_id",), {
                "flow_id": fid, "flow_name": g(row, "Flow_Name"),
                "business_domain": g(row, "Business_Domain"), "goal": g(row, "Goal"),
                "trigger_event": g(row, "Trigger"), "primary_entity": g(row, "Primary_Entity"),
                "source_swagger": g(row, "Source_Swagger"), "notes": g(row, "Notes"),
                "project_id": g(row, "Project_ID") or "sei",
            })
        counts["api_flows"] = len(bundle.get("api_business_flows", []))

        # 2. API_Flow_Steps
        for row in bundle.get("api_flow_steps", []):
            fid = g(row, "Flow_ID"); so = g(row, "Step_Order")
            if not fid or so is None:
                continue
            loader._merge("bf_api_flow_steps", ("flow_id", "step_order"), {
                "flow_id": fid, "step_order": int(float(so)),
                "method": g(row, "Method"), "path": g(row, "Path"),
                "operation_id": g(row, "Operation_ID"),
                "produces_entity": g(row, "Produces_Entity"),
                "consumes_entity": g(row, "Consumes_Entity"), "note": g(row, "Note"),
            })
        counts["api_steps"] = len(bundle.get("api_flow_steps", []))

        # 3. Data_Pipelines
        for row in bundle.get("data_pipelines", []):
            pid = g(row, "Pipeline_ID")
            if not pid:
                continue
            loader._merge("bf_pipelines", ("pipeline_id",), {
                "pipeline_id": pid, "pipeline_name": g(row, "Pipeline_Name"),
                "business_domain": g(row, "Business_Domain"), "archetype": g(row, "Archetype"),
                "direction": g(row, "Direction"), "schedule": g(row, "Schedule"),
                "legacy_system": g(row, "Legacy_System"), "sei_target_type": g(row, "SEI_Target_Type"),
                "sei_target_id": g(row, "SEI_Target_ID"), "source_system": g(row, "Source_System"),
                "target_system": g(row, "Target_System"), "feed_routing": g(row, "Feed_Routing"),
                "in_scope": g(row, "In_Scope"), "goal": g(row, "Goal"), "owner": g(row, "Owner"),
                "project_id": g(row, "Project_ID") or "sei", "notes": g(row, "Notes"),
                "linked_api_flow_id": g(row, "Linked_API_Flow_ID"),
                "associated_feeds": g(row, "Associated_Feeds"), "feed_type": g(row, "Feed_Type"),
                "routing_pattern": g(row, "Routing_Pattern"),
                "compressed_routing": g(row, "Compressed_Routing"),
                "compression_action": g(row, "Compression_Action"),
                "notes_compression": g(row, "Notes_Compression"),
                "legacy_feed_routing": g(row, "Legacy_Feed_Routing"),
            })
        counts["pipelines"] = len(bundle.get("data_pipelines", []))

        # 4. Pipeline_Stages
        for row in bundle.get("pipeline_stages", []):
            pid = g(row, "Pipeline_ID"); so = g(row, "Stage_Order")
            if not pid or so is None:
                continue
            loader._merge("bf_pipeline_stages", ("pipeline_id", "stage_order"), {
                "pipeline_id": pid, "stage": g(row, "Stage"), "stage_order": int(float(so)),
                "member_type": g(row, "Member_Type"), "member_id": g(row, "Member_ID"),
                "member_name": g(row, "Member_Name"), "system": g(row, "System"),
                "note": g(row, "Note"),
            })
        counts["stages"] = len(bundle.get("pipeline_stages", []))

        # 5. Interface_360
        for row in bundle.get("interface_360", []):
            iid = g(row, "Interface_ID")
            if not iid:
                continue
            loader._merge("bf_interfaces", ("interface_id",), {
                "interface_id": iid, "application": g(row, "Application"),
                "integration": g(row, "Integration"), "description": g(row, "Description"),
                "legacy_system": g(row, "Legacy_System"), "sei_target_type": g(row, "SEI_Target_Type"),
                "sei_target_id": g(row, "SEI_Target_ID"), "migration_status": g(row, "Migration_Status"),
                "source_system": g(row, "Source_System"), "target_system": g(row, "Target_System"),
                "direction": g(row, "Direction"), "direct_feed": g(row, "Direct_Feed"),
                "feed_routing": g(row, "Feed_Routing"), "schedule": g(row, "Schedule"),
                "frequency": g(row, "Frequency"), "extract_type": g(row, "Extract_Type"),
                "scope": g(row, "Scope"), "owner": g(row, "Owner"),
                "linked_pipeline_id": g(row, "Linked_Pipeline_ID"),
                "project_id": g(row, "Project_ID") or "sei",
            })
        counts["interfaces"] = len(bundle.get("interface_360", []))

        # 6. Flow_Datapoint_Map (resolve vs dp_registry)
        unresolved = []
        for row in bundle.get("flow_datapoint_map", []):
            fpid = g(row, "Flow_or_Pipeline_ID"); dpn = g(row, "Datapoint_Normalized")
            if not fpid or not dpn:
                continue
            resolved = "Y" if dpn.lower() in known_dps else "N"
            if resolved == "N":
                unresolved.append((fpid, dpn))
            mod = g(row, "Module") or ""
            mid = f"{fpid}|{mod}|{dpn}"[:400]
            loader._merge("bf_flow_datapoint_map", ("map_id",), {
                "map_id": mid, "flow_or_pipeline_id": fpid, "module": mod,
                "datapoint_normalized": dpn, "source_field": g(row, "Source_Field"),
                "source_artifact": g(row, "Source_Artifact"), "direction": g(row, "Direction"),
                "note": g(row, "Note"), "resolved": resolved,
            })
        counts["datapoint_map"] = len(bundle.get("flow_datapoint_map", []))

        # 7/9. Compression_Plan
        for row in bundle.get("compression_plan", []):
            mart = g(row, "Dbt_Gold_Mart")
            if not mart:
                continue
            npipe = g(row, "Number_of_Pipelines")
            loader._merge("bf_compression_plan", ("dbt_gold_mart",), {
                "dbt_gold_mart": mart, "api_flow_id": g(row, "API_Flow_ID"),
                "number_of_pipelines": int(float(npipe)) if npipe else None,
                "sample_pipeline_ids": g(row, "Sample_Pipeline_IDs"),
                "dag_pattern": g(row, "Suggested_Airflow_DAG_Pattern"),
                "compression_ratio": g(row, "Compression_Ratio"), "notes": g(row, "Notes"),
            })
        counts["compression_plan"] = len(bundle.get("compression_plan", []))

        # 8. Compression_Summary
        for row in bundle.get("compression_summary", []):
            metric = g(row, "Metric")
            if not metric:
                continue
            loader._merge("bf_compression_summary", ("metric",), {
                "metric": metric, "value": g(row, "Value"),
            })
        counts["compression_summary"] = len(bundle.get("compression_summary", []))

        loader.commit()

        # mismatch report
        if unresolved:
            log.warning("business_flow: %d Flow_Datapoint_Map rows did NOT resolve to dp_registry:", len(unresolved))
            for fpid, dpn in unresolved[:25]:
                log.warning("   unresolved datapoint '%s' referenced by %s", dpn, fpid)
            if len(unresolved) > 25:
                log.warning("   ... +%d more", len(unresolved) - 25)

        # coverage check: pipelines with no / unmatched Linked_API_Flow_ID won't
        # be assigned to a compression mart.
        try:
            cur.execute("""SELECT COUNT(*) FROM bf_pipelines p
                WHERE p.linked_api_flow_id IS NULL
                   OR NOT EXISTS (SELECT 1 FROM bf_compression_plan c
                                  WHERE c.api_flow_id = p.linked_api_flow_id)""")
            unlinked = cur.fetchone()[0]
            if unlinked:
                log.warning("business_flow: %d pipelines have a missing/unmatched "
                            "Linked_API_Flow_ID — they are NOT assigned to a compression mart", unlinked)
        except Exception:
            pass

        log.info("business_flow: loaded %s; %d unresolved datapoints",
                 counts, len(unresolved))
        return {"counts": counts, "unresolved": unresolved}
